# DataSource Config
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatis_plus
    # 修改驱动为打印sql驱动
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/mybatis_plus
    username: root
    password: root
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
  servlet:
    multipart:
      enabled: true
      # Threshold after which files are written to disk.
      file-size-threshold: 2KB
      # Max file size.
      max-file-size: 200MB
      # Max Request Size
      max-request-size: 215MB

# 配置mybatis-plus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml # 扫描mapper
  global-config:
    db-config:
      id-type: auto # id类型
    banner: true # 启动logo

# 记得把file.upload-dir配置成你自己的存储文件的文件所在的绝对路径
file:
  upload-dir: E:\tmp\file
